# Generated by Django 2.2.4 on 2019-08-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Warna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_warna', models.CharField(max_length=100, null=True)),
                ('gambar', models.ImageField(upload_to='images')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaproduk', models.CharField(max_length=50)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('stok', models.IntegerField()),
                ('gambar_barang', models.ImageField(null=True, upload_to='images')),
                ('keterangan', models.TextField()),
                ('kategori_produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.KategoriBarang')),
            ],
            options={
                'verbose_name_plural': 'Produk',
            },
        ),
    ]
