# Generated by Django 2.2.4 on 2019-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0002_auto_20190815_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
    ]
