# Generated by Django 2.2.4 on 2019-09-02 07:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barang', '0002_kurir_orderitem_pembayaran'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Cart',
        ),
    ]
