# Generated by Django 2.2.4 on 2019-09-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_auto_20190902_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurir',
            old_name='namakurir',
            new_name='nama_kurir',
        ),
        migrations.RenameField(
            model_name='kurir',
            old_name='hargakilo',
            new_name='tarif',
        ),
    ]
