# Generated by Django 2.2.4 on 2019-08-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0003_auto_20190815_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoribarang',
            options={'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name_plural': 'Produk'},
        ),
    ]
