# Generated by Django 2.2.4 on 2019-08-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_auto_20190819_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='kategori_produk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.KategoriBarang'),
        ),
    ]
