# Generated by Django 2.2.4 on 2019-09-03 08:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barang', '0004_auto_20190903_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pesan', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ordered', models.BooleanField(default=False)),
                ('shipping_address', models.TextField(null=True)),
                ('pembayaran', models.CharField(choices=[('cod', 'Cash On Delivery'), ('transfer', 'Bank Transfer')], max_length=20)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='barang.Cart')),
                ('kurir_pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Kurir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
