# Generated by Django 2.2.4 on 2019-08-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0005_produk_kategori_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar_barang',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
