# Generated by Django 2.2.4 on 2019-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tlp_penerima',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
