# Generated by Django 2.2.4 on 2019-09-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_order_tlp_penerima'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='alamat_pengiriman',
        ),
    ]
