# Generated by Django 2.2.4 on 2019-09-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0009_item_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_ordered',
            old_name='harga',
            new_name='harga_ordered',
        ),
        migrations.RenameField(
            model_name='item_ordered',
            old_name='item',
            new_name='item_ordered',
        ),
        migrations.RenameField(
            model_name='item_ordered',
            old_name='ordered',
            new_name='ordered_ordered',
        ),
        migrations.RenameField(
            model_name='item_ordered',
            old_name='quantity',
            new_name='quantity_ordered',
        ),
        migrations.RenameField(
            model_name='item_ordered',
            old_name='user',
            new_name='user_ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='pesan',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item_ordered',
            name='pesan_ordered',
            field=models.TextField(null=True),
        ),
    ]
