# Generated by Django 2.2.4 on 2019-09-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0010_auto_20190910_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(null=True, to='barang.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kurir_pengiriman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.Kurir'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pembayaran',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
