# Generated by Django 2.2.4 on 2019-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0011_auto_20190910_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='barang.Cart'),
        ),
    ]
