# Generated by Django 2.2.4 on 2019-09-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0013_item_ordered_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_ordered',
            name='order',
        ),
    ]
