# Generated by Django 2.2.4 on 2019-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0014_remove_item_ordered_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tanggal_pesan',
            field=models.DateTimeField(blank=True),
        ),
        migrations.DeleteModel(
            name='Item_ordered',
        ),
    ]
