# Generated by Django 2.2.4 on 2019-09-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0015_auto_20190911_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='status_pembayaran',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='telah_dikirim',
        ),
        migrations.AddField(
            model_name='order',
            name='bukti_pembayaran',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='order',
            name='telah_diterima',
            field=models.BooleanField(default=False),
        ),
    ]
