# Generated by Django 2.2.4 on 2019-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0016_auto_20190912_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_pembayaran',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
