# Generated by Django 2.2.4 on 2019-09-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0017_order_total_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='kurir',
            name='tarif',
            field=models.DecimalField(decimal_places=0, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_pembayaran',
            field=models.DecimalField(decimal_places=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=1000000),
        ),
    ]
