# Generated by Django 2.2.4 on 2019-09-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nana_produk',
        ),
        migrations.AddField(
            model_name='product',
            name='harga',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerima', models.CharField(max_length=30, null=True)),
                ('items', models.ManyToManyField(to='testing.Product')),
            ],
        ),
    ]
