# Generated by Django 2.2.4 on 2019-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='namex',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
