# Generated by Django 2.2.4 on 2019-09-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0008_auto_20190903_1502'),
        ('testing', '0002_auto_20190910_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orderiaaa',
        ),
        migrations.RemoveField(
            model_name='orderiaaa',
            name='items',
        ),
        migrations.AddField(
            model_name='orderiaaa',
            name='item_pesan',
            field=models.ManyToManyField(to='barang.Cart'),
        ),
    ]
