# Generated by Django 2.2.4 on 2019-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20190910_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nana_produk', models.CharField(max_length=100)),
                ('jumlah', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
