# Generated by Django 2.2.4 on 2019-08-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPembeli', models.IntegerField()),
                ('idBarang', models.IntegerField()),
                ('jumlahKeranjang', models.IntegerField()),
                ('alamatKirim', models.CharField(max_length=50)),
                ('berat', models.IntegerField()),
                ('totalharga', models.DecimalField(decimal_places=10, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namakurir', models.CharField(max_length=50)),
                ('hargakilo', models.DecimalField(decimal_places=10, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idorder', models.IntegerField()),
                ('idbarang', models.IntegerField()),
                ('jumlahOrder', models.IntegerField()),
                ('ongkir', models.DecimalField(decimal_places=10, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idorder', models.IntegerField()),
                ('statpembayaran', models.CharField(max_length=50)),
            ],
        ),
    ]
