# Generated by Django 2.2.4 on 2019-08-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alamatpembeli',
            options={'verbose_name_plural': 'Alamat'},
        ),
        migrations.AlterModelOptions(
            name='pembeli',
            options={'verbose_name_plural': 'Pembeli'},
        ),
    ]
