# Generated by Django 2.2.4 on 2019-08-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='asds',
        ),
    ]
