# Generated by Django 2.2.4 on 2019-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembeli', '0002_remove_profil_asds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='tlp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
